### ISSUE TITLE
Migration failed with error: DocType Chapter not found

### ISSUE THREAD

**Issue by anandology** [frappe/lms#223]
Migration failed for staging site of mon school after updating to latest version of frappe and community app.

## Traceback

```
(env) root@c54213eb313e:/opt/frappe-bench# bench migrate 
Migrating frappe.localhost
Executing execute:frappe.delete_doc("DocType", "Chapters") in frappe.localhost (frappe)
Success: Done in 0.071s
Executing execute:frappe.delete_doc("DocType", "Lessons") in frappe.localhost (frappe)
Success: Done in 0.02s
Executing execute:frappe.delete_doc("DocType", "Chapter") in frappe.localhost (frappe)
Success: Done in 0.152s
Executing execute:frappe.delete_doc("DocType", "Lesson") in frappe.localhost (frappe)
Success: Done in 0.09s
Executing execute:frappe.delete_doc("DocType", "LMS Topic") in frappe.localhost (frappe)
Success: Done in 0.02s
Executing community.patches.v0_0.rename_chapter_and_lesson_doctype #30-09-2021 in frappe.localhost (frappe)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/opt/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/frappe-bench/env/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/frappe-bench/apps/frappe/frappe/commands/site.py", line 306, in migrate
    migrate(
  File "/opt/frappe-bench/apps/frappe/frappe/migrate.py", line 65, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/opt/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_all
    run_patch(patch)
  File "/opt/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_patch
    if not run_single(patchmodule = patch):
  File "/opt/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 66, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/opt/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 86, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/opt/frappe-bench/apps/community/community/patches/v0_0/rename_chapter_and_lesson_doctype.py", line 16, in execute
    move_chapters()
  File "/opt/frappe-bench/apps/community/community/patches/v0_0/rename_chapter_and_lesson_doctype.py", line 24, in move_chapters
    docs = frappe.get_all("Chapter", fields=["*"])
  File "/opt/frappe-bench/apps/frappe/frappe/__init__.py", line 1465, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/opt/frappe-bench/apps/frappe/frappe/__init__.py", line 1438, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/opt/frappe-bench/apps/frappe/frappe/model/db_query.py", line 106, in execute
    result = self.build_and_run()
  File "/opt/frappe-bench/apps/frappe/frappe/model/db_query.py", line 123, in build_and_run
    args = self.prepare_args()
  File "/opt/frappe-bench/apps/frappe/frappe/model/db_query.py", line 199, in prepare_args
    self.set_order_by(args)
  File "/opt/frappe-bench/apps/frappe/frappe/model/db_query.py", line 707, in set_order_by
    meta = frappe.get_meta(self.doctype)
  File "/opt/frappe-bench/apps/frappe/frappe/__init__.py", line 914, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/opt/frappe-bench/apps/frappe/frappe/model/meta.py", line 35, in get_meta
    meta = Meta(doctype)
  File "/opt/frappe-bench/apps/frappe/frappe/model/meta.py", line 81, in __init__
    super(Meta, self).__init__("DocType", doctype)
  File "/opt/frappe-bench/apps/frappe/frappe/model/document.py", line 110, in __init__
    self.load_from_db()
  File "/opt/frappe-bench/apps/frappe/frappe/model/meta.py", line 86, in load_from_db
    super(Meta, self).load_from_db()
  File "/opt/frappe-bench/apps/frappe/frappe/model/document.py", line 153, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/opt/frappe-bench/apps/frappe/frappe/__init__.py", line 440, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/opt/frappe-bench/apps/frappe/frappe/__init__.py", line 419, in msgprint
    _raise_exception()
  File "/opt/frappe-bench/apps/frappe/frappe/__init__.py", line 373, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType Chapter not found
```

**Comment by anandology** [comment]
Thanks @pateljannat  for #224. How do I fix the issue in my case as the chapter doctype has already been deleted?

**Comment by pateljannat** [comment]
@anandology which site is this? Because when I log in to mon school I can see the chapter doctype.

**Comment by anandology** [comment]
This is staging.mon.school, which I'm running in a docker container.

**Comment by pateljannat** [comment]
`bench set-config maintenance_mode 0`

Try this. Can I get access to the server of this site? I can look into it.

**Comment by anandology** [comment]
Yes, fixed.
