### ISSUE TITLE
I successfully installed lms but Now when i am checkin courses, it is giving some Jinja error

### ISSUE THREAD

**Issue by singhranbir** [frappe/lms#322]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "apps/lms/lms/./www/courses/index.html", line 1, in top-level template code
    {% extends "templates/base.html" %}
  File "apps/frappe/frappe/./templates/base.html", line 82, in top-level template code
    {% block content %}
  File "apps/lms/lms/./www/courses/index.html", line 25, in block "content"
    {% include "lms/templates/course_list.html" %}
  File "apps/lms/lms/./templates/course_list.html", line 8, in top-level template code
    {{ widgets.CourseCard(course=course, read_only=False) }}
  File "env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "apps/lms/lms/widgets.py", line 63, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "apps/lms/lms/./lms/widgets/CourseCard.html", line 1, in top-level template code
    {% set membership = get_membership(course.name, frappe.session.user) %}
  File "env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'get_membership' is undefined
```

**Comment by pateljannat** [comment]
@singhranbir Please share your frappe version and lms version

**Comment by singhranbir** [comment]
![Project-Management-project-management](https://user-images.githubusercontent.com/70106937/161962591-937c836f-6543-4871-a05b-d8e5eabf6fe6.png)

**Comment by katzecz** [comment]
@singhranbir  I have to use version-13 branch on Frappe v13.

**Comment by katzecz** [comment]
> > @singhranbir I have to use version-13 branch on Frappe v13.
> 
> yes, i am using version-13 branch

On screenshot there is main branch. I was experiencing some issues with main branch too when on v13. Main branch works great with v14 to me.

**Comment by singhranbir** [comment]
> > > @singhranbir I have to use version-13 branch on Frappe v13.
> > 
> > 
> > yes, i am using version-13 branch
> 
> On screenshot there is main branch. You have versin-13 branch just for frappe. I was experiencing some issues with main branch too when on v13. Main branch works great with v14 to me.

Thanks, let me Update the same

**Comment by pateljannat** [comment]
@singhranbir yes you will have to use the version-13 branch of LMS with Frappe version-13. Main branch of LMS works with version-14 of Frappe.

**Comment by singhranbir** [comment]
> @singhranbir yes you will have to use the version-13 branch of LMS with Frappe version-13. Main branch of LMS works with version-14 of Frappe.

Yes, Thanks for the Help, Issue is now Resolved.
