### ISSUE TITLE
Getting below error after login 

### ISSUE THREAD

**Issue by ghost** [frappe/lms#343]
Traceback (most recent call last):
  File "apps/frappe/frappe/website/render.py", line 60, in render
    data = render_page_by_language(path)
  File "apps/frappe/frappe/website/render.py", line 210, in render_page_by_language
    return render_page(path)
  File "apps/frappe/frappe/website/render.py", line 227, in render_page
    return build(path)
  File "apps/frappe/frappe/website/render.py", line 235, in build
    return build_page(path)
  File "apps/frappe/frappe/website/render.py", line 259, in build_page
    html = frappe.get_template(context.template).render(context)
  File "env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "env/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "apps/lms/lms/www/dashboard/index.html", line 1, in top-level template code
    {% extends "templates/base.html" %}
  File "apps/frappe/frappe/templates/base.html", line 82, in top-level template code
    {% block content %}
  File "apps/lms/lms/www/dashboard/index.html", line 29, in block 'content'
    {% include "lms/lms/web_template/courses_enrolled/courses_enrolled.html" %}
  File "apps/lms/lms/lms/web_template/courses_enrolled/courses_enrolled.html", line 1, in top-level template code
    {% set enrolled = get_enrolled_courses().in_progress + get_enrolled_courses().completed %}
  File "env/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "env/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'get_enrolled_courses' is undefined

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16416139/172652000-08f9efc7-5c85-4f4d-a388-641fd6292be6.png)

**Comment by pateljannat** [comment]
@techseria What is the version of frappe framework you are using?

**Comment by pateljannat** [comment]
@techseria the main branch of the LMS app only works with the main branch of Frappe Framework.

If you are using version-13 of Frappe Framework, you must use the version-13 branch of the LMS app.

I request you to switch the branch of the LMS app and try again.
