### ISSUE TITLE
Error in running bench migrate - App community is not installed

### ISSUE THREAD

**Issue by hieutrluu** [frappe/lms#349]
**Describe the bug**
Error in running bench migrate after installed lms app

logs
```
Executing community.patches.set_email_preferences in lms.localhost (lms.localhost)

Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 407, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 72, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 47, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_patch
    if not run_single(patchmodule=patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 105, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1434, in get_attr
    throw(_("App {0} is not installed").format(app_name), AppNotInstalledError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AppNotInstalledError: App community is not installed
```

I assume that this error is caused by changing the name of the app from community https://github.com/frappe/lms/issues/7
I ran `bench set-config maintenance_mode 0` and check that the site_config.json does have the line `"maintenance_mode": 0,` from https://github.com/frappe/lms/issues/223
However patches are still apply during `bench migrate` 

**To Reproduce**
1. bench get-app https://github.com/frappe/lms
2. bench install-app lms
3. bench migrate

**Expected behavior**
`bench migrate` succeed

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
Test with both lms branch: main and version-13

Best regards

**Comment by pateljannat** [comment]
@hieutrluu I am unable to replicate this issue on my side.

Are you installing the app on a new site or on any existing site?

**Comment by hieutrluu** [comment]
Sorry for not mentioning it clearer. I install it in an existing site.

Technically if I have not write any code that interact with the lms module doctype it would not matter if I install the lms app on an existing or new site am I correct ?

I tried to install the module on a new site and it does not throw this error at the moment.


In addition The documentation on the home page only show how to use the existing education module

https://docs.erpnext.com/docs/v13/user/manual/en/education/setting-up-lms.

I tried to play around with different doctype in the Lms module however, I am not able to create a course page similar to frappe school or mon school. Any pointer on the documentation or how to set up a similar site to frappe school ?

Best regards.

**Comment by pateljannat** [comment]
@hieutrluu if this is an existing site make sure everything is migrated and up to date. Also, you can refer to [this link](https://www.frappelms.com/introduction) for the documentation of the Frappe LMS app.

**Comment by pateljannat** [comment]
Closing due to inactivity.

**Comment by shantanoo** [comment]
> @hieutrluu if this is an existing site make sure everything is migrated and up to date. Also, you can refer to [this link](https://www.frappelms.com/introduction) for the documentation of the Frappe LMS app.


```
Using domain server:
Name: 1.1
Address: 1.0.0.1#53
Aliases:

Host www.frappelms.com not found: 3(NXDOMAIN)
```
