### ISSUE TITLE
Frappe LMS 'courses' page shows error

### ISSUE THREAD

**Issue by asbasawaraj** [frappe/lms#359]
Just installed 'Frappe LMS' app on a site which already has ERPNext installed. Published a course but on visiting 'courses' page the following error is thrown.

However, installing Frappe LMS on a site without ERPNext app did not result in this issue. 

The issue seems to occur on sites which has ERPNext installed already.

![Screenshot 2022-08-24 at 11 05 44 AM](https://user-images.githubusercontent.com/11595602/186337391-5d57b9ac-fc37-46e5-b0cc-144784d7966e.png)

Traceback (most recent call last):
  File "apps/frappe/frappe/website/render.py", line 60, in render
    data = render_page_by_language(path)
  File "apps/frappe/frappe/website/render.py", line 210, in render_page_by_language
    return render_page(path)
  File "apps/frappe/frappe/website/render.py", line 227, in render_page
    return build(path)
  File "apps/frappe/frappe/website/render.py", line 235, in build
    return build_page(path)
  File "apps/frappe/frappe/website/render.py", line 261, in build_page
    html = frappe.get_template(context.template).render(context)
  File "env/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "apps/lms/lms/www/courses/course.html", line 209, in top-level template code
    {{ frappe.utils.flt(avg_rating, frappe.get_system_settings("float_precision") or 3) }} Rating
  File "apps/frappe/frappe/templates/base.html", line 82, in top-level template code
    {% block content %}
  File "apps/lms/lms/www/courses/course.html", line 13, in block 'content'
    {{ CourseOutlineAndCreator(course) }}
  File "env/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "env/lib/python3.7/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
  File "apps/lms/lms/www/courses/course.html", line 117, in template
    {{ widgets.MemberCard(member=course.get_instructor(), show_course_count=True, dimension_class="member-card-large") }}
  File "env/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "apps/lms/lms/widgets.py", line 63, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "env/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "apps/lms/lms/lms/widgets/MemberCard.html", line 3, in top-level template code
    {{ widgets.Avatar(member=member, avatar_class=avatar_class) }}
  File "env/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "apps/lms/lms/widgets.py", line 63, in __call__
    return env.get_or_select_template(paths).render(kwargs)
  File "env/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "apps/lms/lms/lms/widgets/Avatar.html", line 1, in top-level template code
    {% set color = member.get_palette() %}
  File "env/lib/python3.7/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "env/lib/python3.7/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'frappe.core.doctype.user.user.User object' has no attribute 'get_palette' 

**Additional context**
Tried this in Frappe Cloud site.

Installed Apps
ERPNext: v13.36.4 (HEAD)
Erpnext Telegram Integration: v1.0.1 (HEAD)
Frappe Framework: v13.38.0 (HEAD)
LMS: v0.0.1 (HEAD)
Nextcloud Integration: v0.0.1 (HEAD)
Wiki: v0.0.1 (HEAD)

**Comment by pateljannat** [comment]
@asbasawaraj The main branch of the Frappe LMS app works with the develop branch or version-14 of ERPNext. Likewise, the version-13 branch of Frappe LMS goes with the version-13 branch of ERPNext.

You can do one of the two things to fix this.
 1. Change the branch of ERPNext and Frappe to version-14 or develop.
 2. Change the branch of Frappe LMS app to version-13.

Let me know if this works.

**Comment by asbasawaraj** [comment]
I think I am already on LMS version-13.
![Screenshot 2022-08-24 at 11 49 09 AM](https://user-images.githubusercontent.com/11595602/186347933-bd2516fe-cfce-4c20-a8c4-f183f0f4a70e.png)

**Comment by pateljannat** [comment]
@asbasawaraj can you share the site details?

**Comment by asbasawaraj** [comment]
Hi Jannat,

You can see the issue here.

https://apexsoftwaretech.frappe.cloud/courses

Thanks

**Comment by pateljannat** [comment]
@asbasawaraj I updated your site on FC and the page is not leading without any errors.

**Comment by asbasawaraj** [comment]
Wow! Awesome! Thanks Jannat.
