### ISSUE TITLE
Error adding Course Lesson

### ISSUE THREAD

**Issue by QHD-sp** [frappe/lms#418]
**Describe the bug**

https://user-images.githubusercontent.com/114915243/199161369-60c392c6-b784-4c87-9d2b-c1c3369405fb.mp4

![image](https://user-images.githubusercontent.com/114915243/199162672-9d009d4e-8aa7-43ca-9f6d-084dcbba9d10.png)

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    html = self.render_template()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 232, in render_template
    html = frappe.render_template(self.source, self.context, safe_render=safe_render)
  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template
    return get_jenv().from_string(template).render(context)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 285, in top-level template code
  File "apps/frappe/frappe/templates/base.html", line 82, in top-level template code
    {% block content %}
  File "<template>", line 35, in block 'content'
  File "env/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "env/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 126, in template
  File "env/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
TypeError: render_html() missing 2 required positional arguments: 'youtube' and 'quiz_id'

**To Reproduce**
1. Create a Course Lesson:  "Test bài học"
2. Add YouTube Video URL and Quiz ID
3. Save
4. Visit Courses website
5. Select the course with the newly created Course Lesson
6. Scroll down to Course Conten
7. Click '"Test lesson"
8. See Error

**Expected behavior**

1. Please guide me how to add new standard Course Lesson.
2. Course Lesson will be displayed on the website and no more error messages.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by pateljannat** [comment]
Is your site updated to the latest version?
