### ISSUE TITLE
Failed to create a new User

### ISSUE THREAD

**Issue by marianolop** [frappe/lms#647]
**Describe the bug**
Follow the steps to run the app, clone, cd docker and then run docker-compose. When I can enter the platform, I try to create a new user and I get the error.

**To Reproduce**
1. Clone the repo "git clone https://github.com/frappe/lms"
2. Cd lms/docker
3. docker-compose up
4. enter to http://localhost:8000/
5. Log as Administrator pass: admin
6. Go to user and create one, enter data and save
7. You'll get this error "AttributeError: 'NoneType' object has no attribute 'encode'"

**Expected behavior**
It should create the user

**Screenshots**
![Captura de pantalla 2023-10-16 a la(s) 18 10 56](https://github.com/frappe/lms/assets/120674571/21a71de8-b512-450e-90ae-08ca14f03a74)

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma (with preious didn't work either)
 - Browser chrome, safari, etc
 - Version latest version
 - Mac Book Pro with M1 and Intel

**Additional context**
Full log when click in "Copy error to clipboard"
### App Versions
```
{
	"frappe": "15.0.0-dev",
	"lms": "1.0.0"
}
```
### Route
```
Form/User/new-user-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 105, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 224, in save
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 313, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1126, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 953, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1324, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 950, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 204, in on_update
    self.send_password_notification(self.__new_password)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 357, in send_password_notification
    self.send_welcome_mail_to_user()
  File "apps/frappe/frappe/core/doctype/user/user.py", line 441, in send_welcome_mail_to_user
    self.send_login_mail(
  File "apps/frappe/frappe/core/doctype/user/user.py", line 481, in send_login_mail
    frappe.sendmail(
  File "apps/frappe/frappe/__init__.py", line 758, in sendmail
    builder.process(send_now=now)
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 705, in process
    queue_data = self.as_dict(include_recipients=False)
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 749, in as_dict
    mail = self.prepare_email_content()
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 674, in prepare_email_content
    sender=self.sender,
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 572, in sender
    return email_account.default_sender
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 332, in default_sender
    return email.utils.formataddr((self.name, self.get("email_id")))
  File "/home/frappe/.pyenv/versions/3.10.12/lib/python3.10/email/utils.py", line 91, in formataddr
    address.encode('ascii')
AttributeError: 'NoneType' object has no attribute 'encode'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"User\",\"name\":\"new-user-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"enabled\":1,\"country\":\"United States\",\"language\":\"en-US\",\"user_category\":\"Business Owner\",\"send_welcome_email\":1,\"unsubscribed\":0,\"attire\":\"Casual Wear\",\"collaboration\":\"Individual Work\",\"role\":\"Clearly Defined Role\",\"location_preference\":\"Travel\",\"time\":\"Flexible Time\",\"company_type\":\"Corporate Organization\",\"mute_sounds\":0,\"desk_theme\":\"Light\",\"logout_all_sessions\":1,\"document_follow_notify\":0,\"document_follow_frequency\":\"Daily\",\"follow_created_documents\":0,\"follow_commented_documents\":0,\"follow_liked_documents\":0,\"follow_assigned_documents\":0,\"follow_shared_documents\":0,\"thread_notify\":1,\"send_me_a_copy\":0,\"allowed_in_mentions\":1,\"simultaneous_sessions\":1,\"user_type\":\"System User\",\"bypass_restrict_ip_check_if_2fa_enabled\":0,\"onboarding_status\":\"{}\",\"__run_link_triggers\":1,\"email\":\"mariano.lopez@halopowered.com\",\"first_name\":\"Mariano\"}"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.save",
	"request_id": null
}
```
### Response Data
```
{
	"exc_type": "DoesNotExistError",
	"exception": "AttributeError: 'NoneType' object has no attribute 'encode'",
	"_server_messages": "[\"{\\\"message\\\": \\\"Adding System Manager to this User as there must be atleast one System Manager\\\", \\\"title\\\": \\\"Message\\\"}\"]"
}
```

**Comment by marianolop** [comment]
@pateljannat can you please help me with this, it's a basic functionality that should work

**Comment by pateljannat** [comment]
@marianolop it fails while trying to send the welcome email. Have you set up an email account?

**Comment by marianolop** [comment]
@pateljannat could you please tell me where do I set up that?

**Comment by pateljannat** [comment]
You can follow this guide

https://docs.erpnext.com/docs/user/manual/en/email-account

If this is just a local test site, you can also skip sending email by unchecking **Send Welcome Email** and the user creation would still work.

**Comment by marianolop** [comment]
ah excellent!

**Comment by pateljannat** [comment]
@marianolop is user creation working for you now?

**Comment by marianolop** [comment]
@pateljannat it's working perfect! Thanks!

**Comment by marianolop** [comment]
Sorry! in stage wasn't working and we fixed on friday and locally it's
working now

Bye!
