### ISSUE TITLE
can't save batch edit record

### ISSUE THREAD

**Issue by coolcoolhua** [frappe/lms#753]
### App Versions
```
{
	"frappe": "16.0.0-dev",
	"lms": "1.0.0"
}
```
### Route
```
Form/LMS Batch/CLS-00033
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1796, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 335, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 371, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 959, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 956, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/lms/lms/lms/doctype/lms_batch/lms_batch.py", line 31, in validate
    self.send_confirmation_mail()
  File "apps/lms/lms/lms/doctype/lms_batch/lms_batch.py", line 69, in send_confirmation_mail
    self.send_mail(student)
  File "apps/lms/lms/lms/doctype/lms_batch/lms_batch.py", line 96, in send_mail
    frappe.sendmail(
  File "apps/frappe/frappe/__init__.py", line 867, in sendmail
    return builder.process(send_now=now)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 699, in process
    queue_data = self.as_dict(include_recipients=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 744, in as_dict
    mail = self.prepare_email_content()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 668, in prepare_email_content
    sender=self.sender,
           ^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 566, in sender
    return email_account.default_sender
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 346, in default_sender
    return email.utils.formataddr((self.name, self.get("email_id")))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/.pyenv/versions/3.11.6/lib/python3.11/email/utils.py", line 91, in formataddr
    address.encode('ascii')
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"CLS-00033\",\"owner\":\"Administrator\",\"creation\":\"2024-03-13 18:43:44.272757\",\"modified\":\"2024-03-14 09:48:39.639517\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"课程集合1\",\"start_date\":\"2024-03-15\",\"end_date\":\"2024-04-25\",\"start_time\":\"18:42:15\",\"end_time\":\"23:41:58\",\"published\":1,\"allow_self_enrollment\":1,\"medium\":\"Online\",\"category\":\"\",\"seat_count\":100,\"description\":\"测试\",\"batch_details_raw\":\"\",\"batch_details\":\"<div class=\\\"ql-editor read-mode\\\"><p>测试一下</p></div>\",\"meta_image\":\"\",\"show_live_class\":0,\"allow_future\":1,\"paid_batch\":0,\"amount\":0,\"currency\":\"\",\"amount_usd\":0,\"doctype\":\"LMS Batch\",\"courses\":[{\"name\":2,\"owner\":\"Administrator\",\"creation\":\"2024-03-13 18:43:44.272757\",\"modified\":\"2024-03-14 09:48:39.639517\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"course\":\"7d80dbc53c\",\"title\":\"测试内容1\",\"parent\":\"CLS-00033\",\"parentfield\":\"courses\",\"parenttype\":\"LMS Batch\",\"doctype\":\"Batch Course\"},{\"name\":3,\"owner\":\"Administrator\",\"creation\":\"2024-03-13 18:43:44.272757\",\"modified\":\"2024-03-14 09:48:39.639517\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"course\":\"873ec1d99a\",\"title\":\"金融机构-财富和个人银行体验项目\",\"parent\":\"CLS-00033\",\"parentfield\":\"courses\",\"parenttype\":\"LMS Batch\",\"doctype\":\"Batch Course\"}],\"timetable_legends\":[],\"timetable\":[],\"assessment\":[{\"name\":\"f193db5c76\",\"owner\":\"Administrator\",\"creation\":\"2024-03-13 18:43:44.272757\",\"modified\":\"2024-03-14 09:48:39.639517\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"assessment_type\":\"LMS Assignment\",\"assessment_name\":\"ASG-00028\",\"parent\":\"CLS-00033\",\"parentfield\":\"assessment\",\"parenttype\":\"LMS Batch\",\"doctype\":\"LMS Assessment\"}],\"students\":[{\"name\":\"edea056074\",\"owner\":\"student@example.com\",\"creation\":\"2024-03-14 09:49:06.298177\",\"modified\":\"2024-03-14 09:49:06.298177\",\"modified_by\":\"student@example.com\",\"docstatus\":0,\"idx\":1,\"student\":\"student@example.com\",\"student_name\":\"Student\",\"username\":\"student\",\"confirmation_email_sent\":0,\"parent\":\"CLS-00033\",\"parentfield\":\"students\",\"parenttype\":\"LMS Batch\",\"doctype\":\"Batch Student\"}],\"__last_sync_on\":\"2024-03-18T09:33:07.542Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700033531499127947171": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 619,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'encode'",
	"exc_type": "AttributeError",
	"_exc_source": "lms (app)"
}
```

**Comment by pateljannat** [comment]
@coolcoolhua this looks like an issue with your email account setup.

**Comment by pateljannat** [comment]
@coolcoolhua you shouldn't be facing this issue again. I have added a condition that checks if an outgoing email account is set. Only then does it trigger an email. Else not.
