### ISSUE TITLE
Uncaught Server Exception: There was an error building this page, https://frappe.school/users/mesfin-tsegaye

### ISSUE THREAD

**Issue by codewithmesfin** [frappe/lms#772]
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/lms/lms/page_renderers.py", line 103, in render
    return render_portal_page("profiles/profile", username=username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/lms/lms/page_renderers.py", line 109, in render_portal_page
    return page.render()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 521, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 94, in get_html
    self.set_pymodule()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 146, in set_pymodule
    if os.path.exists(os.path.join(self.app_path, self.pymodule_path)):
                                   ^^^^^^^^^^^^^
AttributeError: 'TemplatePage' object has no attribute 'app_path'

**Comment by pateljannat** [comment]
Fixed with #774
