### ISSUE TITLE
error on creating new site for lms

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#904]
https://frappecloud.com/api/method/press.api.saas.validate_account_request?key=Nq9PWrGhMAq5j1jLlp9Q2bB3UBvh6Kh1
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1795, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/saas.py", line 219, in validate_account_request
    if app_info.headless:
AttributeError: 'tuple' object has no attribute 'headless'
Status: 500

**Comment by pateljannat** [comment]
@thida-bcn this seems like an issue on press
