### ISSUE TITLE
LMS with ERPNext creates invalid user

### ISSUE THREAD

**Issue by geverit4** [frappe/lms#991]
**Describe the bug**
When LMS is installed on a Version 15 ERPNext deployment, the "Notification Settings" document is not created for any user.  It looks like the LMS interferes with the User document creation and does not invoke the after_insert in user.py which is responsible for creating a Notification Settings document. 

When a user then tries to log in, they are presented with the following stack dump: 

Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 27, in get_context
    boot = frappe.sessions.get()
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 140, in get
    bootinfo = get_bootinfo()
               ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/boot.py", line 75, in get_bootinfo
    bootinfo.notification_settings = get_notification_settings()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/boot.py", line 401, in get_notification_settings
    return frappe.get_cached_doc("Notification Settings", frappe.session.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1207, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1333, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 172, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: Notification Settings user@example.com not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 523, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 29, in get_context
    raise frappe.SessionBootFailed from e
frappe.exceptions.SessionBootFailed

**To Reproduce**
1. Install ERPNext version 15
2. Install LMS (either develop or main branch - both cause the problem)
3. Run the site setup, which creates a System Manager account
4. Login as the system manager account.  
5. Behold the stack trace above.

**Expected behavior**
This ONLY happens with the LMS installed, as far as I can tell.  HRMS and ERPNext and a couple of custom apps I have all work fine.  

**Additional context**
Even worse, just having the LMS on the bench and creating a new site even without the LMS installed on the site will cause different errors when attempting to setup the new site.  That seems very strange to me, since why would the LMS interfere with a site where it is not installed?

I believe the latest versions of the LMS are not compatible with ERPNext version 15.

**Comment by pateljannat** [comment]
This was fixed with https://github.com/frappe/lms/pull/994
